<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AswinikumarsMBP.lan" name="twc.Automation.ExecutableTestCases.smokeTestCases" tests="141" failures="28" timestamp="13 Oct 2022 08:55:09 GMT" time="1370.307" errors="0">
  <testcase name="Validate_Marquee_st_Custom_param" time="0.128" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_cnd_Custom_param" time="0.155" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :cnd value: pcld is not matched with the expected value: 30">
      <![CDATA[java.lang.AssertionError: Custom Parameter :cnd value: pcld is not matched with the expected value: 30
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Feed1_cnd_Custom_param(smokeTestCases.java:1560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Feed1_cnd_Custom_param -->
  <testcase name="Validate_HourlyDetails_tmpc_Custom_param" time="0.140" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :tmpc value: 32 is not matched with the expected value: 31">
      <![CDATA[java.lang.AssertionError: Custom Parameter :tmpc value: 32 is not matched with the expected value: 31
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_HourlyDetails_tmpc_Custom_param(smokeTestCases.java:1658)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_HourlyDetails_tmpc_Custom_param -->
  <testcase name="Validate_Criteo_SDK_config_app_Call_cpId_parameter" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: cpId validation skipped">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: cpId validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Criteo_SDK_config_app_call_parameter(Utils.java:6696)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_config_app_Call_cpId_parameter(smokeTestCases.java:838)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_config_app_Call_cpId_parameter -->
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day7adcall_FTL" time="0.075" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_Air_Quality_contentpage_adCall_FTL" time="0.255" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_aid_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_ct_Custom_param" time="0.147" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_dynght_Custom_param" time="0.127" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aaxSlot_feed1_preroladcall_killLaunch" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: f4b66249-b6eb-4155-9d90-1e2b04487c99 is not present">
      <![CDATA[java.lang.AssertionError: slot id: f4b66249-b6eb-4155-9d90-1e2b04487c99 is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aaxSlot_feed1_preroladcall_killLaunch(smokeTestCases.java:794)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aaxSlot_feed1_preroladcall_killLaunch -->
  <testcase name="Validate_Feed1_dynght_Custom_param" time="0.138" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Case_Verify_sz_Radar_Maps_deatailspage_adCall_FTL" time="0.285" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2Fmaps not found in charles session, hence Custom Parameter: sz validation skipped">
      <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2Fmaps not found in charles session, hence Custom Parameter: sz validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Noncustom_param_val_of_gampad(Utils.java:4387)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_Case_Verify_sz_Radar_Maps_deatailspage_adCall_FTL(smokeTestCases.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_Case_Verify_sz_Radar_Maps_deatailspage_adCall_FTL -->
  <testcase name="Validate_HourlyDetails_ltv_Custom_param" time="0.076" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_zip_Custom_param" time="0.129" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_outdoor_detailpage_adcall_FTL" time="0.259" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_ltv_Custom_param" time="0.081" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_description_url_Custom_param" time="0.271" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Daily_Details_ltv_Custom_param" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_csmEnabled" time="0.011" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: csmEnabled validation skipped">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: csmEnabled validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Criteo_SDK_config_app_call_response_parameter(Utils.java:7044)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_csmEnabled(smokeTestCases.java:900)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_csmEnabled -->
  <testcase name="Smoke_Test_Verify_hourly2_detailpage_bigad_adcall_FTL" time="0.045" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_dynght_Custom_param" time="0.159" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_slotName_Custom_param" time="0.077" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Verify_SafetyAndPreparednessCard_AdCall" time="0.304" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_lang_Custom_param" time="0.087" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Case_Verify_Radar_Maps_deatailspage_adCall_FTL" time="0.288" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2Fmaps ad call is not present">
      <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2Fmaps ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyPubadCal(Utils.java:236)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_Case_Verify_Radar_Maps_deatailspage_adCall_FTL(smokeTestCases.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_Case_Verify_Radar_Maps_deatailspage_adCall_FTL -->
  <testcase name="Validate_Criteo_SDK_config_app_Call_sdkVersion_parameter" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: sdkVersion validation skipped">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: sdkVersion validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Criteo_SDK_config_app_call_parameter(Utils.java:6696)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_config_app_Call_sdkVersion_parameter(smokeTestCases.java:827)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_config_app_Call_sdkVersion_parameter -->
  <testcase name="Validate_Marquee_im_Custom_param" time="0.077" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_tmpr_Custom_param" time="0.136" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_st_Custom_param" time="0.131" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_tmpr_Custom_param" time="0.126" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_health_and_activities_Allergy_spotlight_pos_custumparam" time="0.278" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_adid_Custom_param" time="0.090" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_locale_Custom_param" time="0.139" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_tmp_Custom_param" time="0.149" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_Hourly2_bigaddetails_preroll_adcall_killLaunch" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: 4fbed16a-cc6f-4cb1-94f7-81465acbd47e is not present">
      <![CDATA[java.lang.AssertionError: slot id: 4fbed16a-cc6f-4cb1-94f7-81465acbd47e is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_Hourly2_bigaddetails_preroll_adcall_killLaunch(smokeTestCases.java:757)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_Hourly2_bigaddetails_preroll_adcall_killLaunch -->
  <testcase name="Validate_HourlyDetails_plat_Custom_param" time="0.084" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_Daily_details_preroll_adcall" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_sod_Custom_param" time="0.087" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_lnid_Custom_param" time="0.262" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day4adcall_FTL" time="0.377" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_health_and_activities_coldFlu_contenPage_adcall_FTL" time="0.294" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_ltv_Custom_param" time="0.081" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_Hourly3_bigaddetails_preroll_adcall_killLaunch" time="0.007" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: 72634dc9-b59f-4b2c-b281-bb3be291b7b6 is not present">
      <![CDATA[java.lang.AssertionError: slot id: 72634dc9-b59f-4b2c-b281-bb3be291b7b6 is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_Hourly3_bigaddetails_preroll_adcall_killLaunch(smokeTestCases.java:769)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_Hourly3_bigaddetails_preroll_adcall_killLaunch -->
  <testcase name="Smoke_Test_Verifying_newdailydetails_day7adcall_FTL" time="27.150" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_content_url_Custom_param" time="0.220" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_hourly_detailpage_adcall_FTL" time="67.285" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_ord_Custom_param" time="0.083" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_st_Custom_param" time="0.135" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verifying_newdailydetails_day3adcall_FTL" time="27.016" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_plat_Custom_param" time="0.139" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verifying_newdailydetails_day5adcall_FTL" time="27.067" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_cnd_Custom_param" time="0.147" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :cnd value: pcld is not matched with the expected value: 30">
      <![CDATA[java.lang.AssertionError: Custom Parameter :cnd value: pcld is not matched with the expected value: 30
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_HourlyDetails_cnd_Custom_param(smokeTestCases.java:1574)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_HourlyDetails_cnd_Custom_param -->
  <testcase name="Validate_Marquee_lang_Custom_param" time="0.083" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test__Verifying_Bcp_apicall_URL_killLaunch" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Lotame :API Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: Lotame :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAPICal(Utils.java:919)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test__Verifying_Bcp_apicall_URL_killLaunch(smokeTestCases.java:717)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test__Verifying_Bcp_apicall_URL_killLaunch -->
  <testcase name="Validate_Feed1_tmp_Custom_param" time="0.144" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_pos_Custom_param" time="0.074" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_pos_Custom_param" time="0.089" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_sz_AirQuality_contentpage_adCall_FTL" time="0.287" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_tmpc_Custom_param" time="0.146" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :tmpc value: 32 is not matched with the expected value: 31">
      <![CDATA[java.lang.AssertionError: Custom Parameter :tmpc value: 32 is not matched with the expected value: 31
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Marquee_tmpc_Custom_param(smokeTestCases.java:1632)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Marquee_tmpc_Custom_param -->
  <testcase name="Validate_dailydetails_dt_Custom_param" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_dailydetails_dynght_Custom_param" time="0.010" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :dynght value: nl is not matched with the expected value NotNull">
      <![CDATA[java.lang.AssertionError: Custom Parameter :dynght value: nl is not matched with the expected value NotNull
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:3977)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_dailydetails_dynght_Custom_param(smokeTestCases.java:462)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_dailydetails_dynght_Custom_param -->
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day3adcall_FTL" time="0.018" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_locale_Custom_param" time="0.160" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_CaseVerify_WeatherFXAPI_url_KillLaunch" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="WFXTrigger :API Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: WFXTrigger :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAPICal(Utils.java:919)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_CaseVerify_WeatherFXAPI_url_KillLaunch(smokeTestCases.java:692)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_CaseVerify_WeatherFXAPI_url_KillLaunch -->
  <testcase name="Smoke_Test_Verifying_newdailydetails_day1adcall_FTL" time="19.251" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Criteo_SDK_Initialization_API_Call_Response_Code" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence response code validation is failed">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence response code validation is failed
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyCriteo_config_app_Call_ReponseStatusCode(Utils.java:6998)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_Initialization_API_Call_Response_Code(smokeTestCases.java:873)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_Initialization_API_Call_Response_Code -->
  <testcase name="Validate_HourlyDetails_ct_Custom_param" time="0.133" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_lang_Custom_param" time="0.095" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_zip_Custom_param" time="0.150" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="validate_HomeScreen_marquee_sod_Custom_param" time="0.087" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_IMA_SDK_version" time="0.225" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verifying_newdailydetails_day6adcall_FTL" time="27.013" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_mr_Custom_param" time="0.070" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_mapsdetails_preload_adcall" time="0.009" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: 5db1161b-b504-4640-9496-dfe6284f84ab is not present">
      <![CDATA[java.lang.AssertionError: slot id: 5db1161b-b504-4640-9496-dfe6284f84ab is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_mapsdetails_preload_adcall(smokeTestCases.java:782)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_mapsdetails_preload_adcall -->
  <testcase name="Validate_HourlyDetails_tf_Custom_param" time="0.084" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_adid_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_health_and_activities_Running_contenPage_adcall_FTL" time="0.490" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_dma_Custom_param" time="0.142" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_tile_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Amazon_SDK_adsdk_parameter" time="0.012" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Android10 call is not present in Charles session, hence Custom Parameter: adsdk validation skipped">
      <![CDATA[java.lang.AssertionError: Android10 call is not present in Charles session, hence Custom Parameter: adsdk validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Amazon_aax_call_parameter(Utils.java:8505)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Amazon_SDK_adsdk_parameter(smokeTestCases.java:885)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Amazon_SDK_adsdk_parameter -->
  <testcase name="Smoke_Test_Verify_hourly3__bigad_detailpage_adcall_FTL" time="0.049" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_preload_video_adcall" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: f71b7e17-6e34-4f6c-98f6-bbbe9f55586c is not present">
      <![CDATA[java.lang.AssertionError: slot id: f71b7e17-6e34-4f6c-98f6-bbbe9f55586c is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_preload_video_adcall(smokeTestCases.java:804)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_preload_video_adcall -->
  <testcase name="Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_liveBiddingEnabled" time="0.010" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: liveBiddingEnabled validation skipped">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: liveBiddingEnabled validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Criteo_SDK_config_app_call_response_parameter(Utils.java:7044)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_liveBiddingEnabled(smokeTestCases.java:914)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_Initialization_API_Call_Response_Parameter_liveBiddingEnabled -->
  <testcase name="Smoke_Test_CaseVerify_Homescreen_marquee_adCall_FTL" time="589.050" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Criteo_SDK_config_app_Call_bundleId_parameter" time="0.013" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: bundleId validation skipped">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence Custom Parameter: bundleId validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Criteo_SDK_config_app_call_parameter(Utils.java:6696)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_config_app_Call_bundleId_parameter(smokeTestCases.java:847)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_config_app_Call_bundleId_parameter -->
  <testcase name="Validate_Marquee_slotName_Custom_param" time="0.081" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_ord_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_sz_hourly_detailpage_adcall_FTL" time="0.044" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_ver_Custom_param" time="0.083" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_verifying_sz_feed_1_adcall_FTL" time="0.263" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_plist_Custom_param" time="0.238" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_nonRefresh_HourlyDetails_mr_Custom_param" time="0.079" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Verifying_Factual_locationwfxtriggerscom_apiCall_supressing" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_tmpc_Custom_param" time="0.144" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :tmpc value: 32 is not matched with the expected value: 31">
      <![CDATA[java.lang.AssertionError: Custom Parameter :tmpc value: 32 is not matched with the expected value: 31
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Feed1_tmpc_Custom_param(smokeTestCases.java:1645)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Feed1_tmpc_Custom_param -->
  <testcase name="Validate_Marquee_tmp_Custom_param" time="0.166" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_GMA_SDK_version" time="0.078" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :js value: afma-sdk-a-v223104999.221310000.1 is not matched with the expected value afma-sdk-a-v214106999.212910000.1">
      <![CDATA[java.lang.AssertionError: Custom Parameter :js value: afma-sdk-a-v223104999.221310000.1 is not matched with the expected value afma-sdk-a-v214106999.212910000.1
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_Noncustom_param_val_of_gampad(Utils.java:6643)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_GMA_SDK_version(smokeTestCases.java:1983)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_GMA_SDK_version -->
  <testcase name="Validate_PreRollVideo_cmsid_Custom_param" time="297.167" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verifying_newdailydetails_day2adcall_FTL" time="27.056" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_sz_hourly2_detailpage_bigad_adcall_FTL" time="0.046" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_Hourly_preroll_adcall_killLaunch" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: 9be28769-4207-4d51-8063-dc8e645383b2 is not present">
      <![CDATA[java.lang.AssertionError: slot id: 9be28769-4207-4d51-8063-dc8e645383b2 is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_Hourly_preroll_adcall_killLaunch(smokeTestCases.java:734)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_Hourly_preroll_adcall_killLaunch -->
  <testcase name="Validate_Marquee_plat_Custom_param" time="219.162" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_ttid_Custom_param" time="0.320" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_cnd_Custom_param" time="0.182" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="Custom Parameter :cnd value: pcld is not matched with the expected value: 30">
      <![CDATA[java.lang.AssertionError: Custom Parameter :cnd value: pcld is not matched with the expected value: 30
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.validate_custom_param_val_of_gampad(Utils.java:4155)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Marquee_cnd_Custom_param(smokeTestCases.java:1547)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Marquee_cnd_Custom_param -->
  <testcase name="Smoke_Test_Verify_sz_hourly3__bigad_detailpage_adcall_FTL" time="0.055" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_ord_Custom_param" time="0.081" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_ver_Custom_param" time="0.077" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_slotName_Custom_param" time="0.078" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_CaseVerify_Today_details_page_iu_FTL" time="0.292" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_dailydetails_mnth_Custom_param" time="0.007" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_pos_Custom_param" time="0.003" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_health_and_activities_Allergy_contenPage_adcall_FTL" time="0.360" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_mr_Custom_param" time="0.091" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_tile_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Verify_AlertCenterAd" time="0.717" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_aid_Custom_param" time="0.085" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_ver_Custom_param" time="0.076" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day6adcall_FTL" time="0.018" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_sod_Custom_param" time="0.105" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_adid_Custom_param" time="0.080" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_ct_Custom_param" time="0.146" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day2adcall_FTL" time="0.015" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_PreRollVideo_vid_Custom_param" time="0.001" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_amazon_aax_Hourly1_bigaddetails_preroll_adcall_killLaunch" time="0.008" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="slot id: 08f0ccea-cab5-449c-963d-dc57ed9ee87d is not present">
      <![CDATA[java.lang.AssertionError: slot id: 08f0ccea-cab5-449c-963d-dc57ed9ee87d is not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAAX_SlotId(Utils.java:543)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_amazon_aax_Hourly1_bigaddetails_preroll_adcall_killLaunch(smokeTestCases.java:745)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_amazon_aax_Hourly1_bigaddetails_preroll_adcall_killLaunch -->
  <testcase name="Validate_HourlyDetails_tile_Custom_param" time="0.090" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_sz_hourly1_detailpage_bigad_adcall_FTL" time="0.043" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_verifying_feed_1adcall_FTL" time="0.345" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_locale_Custom_param" time="0.130" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_dma_Custom_param" time="0.143" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Marquee_tmpr_Custom_param" time="0.140" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_sz_Verifying_newdailydetails_day5adcall_FTL" time="0.017" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_CaseVerify_turbo_url_KillLaunch" time="0.011" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="TurboApi :API Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: TurboApi :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyAPICal(Utils.java:919)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Smoke_Test_CaseVerify_turbo_url_KillLaunch(smokeTestCases.java:708)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Smoke_Test_CaseVerify_turbo_url_KillLaunch -->
  <testcase name="Smoke_Test_CaseVerify_sz_Homescreen_marquee_adCall_FTL" time="0.264" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Feed1_dma_Custom_param" time="0.128" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_Criteo_SDK_Bidder_API_Call_Response_Code" time="0.012" classname="twc.Automation.ExecutableTestCases.smokeTestCases">
    <failure type="java.lang.AssertionError" message="bidder.criteo.com/config/app call is not present in Charles session, hence response code validation is failed">
      <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app call is not present in Charles session, hence response code validation is failed
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.General.Utils.verifyCriteo_inapp_v2_Call_ReponseStatusCode(Utils.java:6735)
	at twc.Automation.ExecutableTestCases.smokeTestCases.Validate_Criteo_SDK_Bidder_API_Call_Response_Code(smokeTestCases.java:860)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Criteo_SDK_Bidder_API_Call_Response_Code -->
  <testcase name="Verify_sz_AlertCenterAd" time="0.302" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verifying_newdailydetails_day4adcall_FTL" time="27.357" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_zip_Custom_param" time="0.147" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_hourly1_detailpage_bigad_adcall_FTL" time="0.051" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_dailydetails_fcnd_Custom_param" time="0.070" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Smoke_Test_Verify_health_and_activities_Bot_Beach_contenPage_adcall_FTL" time="0.341" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
  <testcase name="Validate_HourlyDetails_aid_Custom_param" time="0.086" classname="twc.Automation.ExecutableTestCases.smokeTestCases"/>
</testsuite> <!-- twc.Automation.ExecutableTestCases.smokeTestCases -->
